//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Cliente.
        /// </summary>
        internal static string btn_add_client_Text {
            get {
                return ResourceManager.GetString("btn_add_client.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Funcionário.
        /// </summary>
        internal static string btn_add_employee_Text {
            get {
                return ResourceManager.GetString("btn_add_employee.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Sabores.
        /// </summary>
        internal static string btn_add_flavours_Text {
            get {
                return ResourceManager.GetString("btn_add_flavours.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Ingredientes.
        /// </summary>
        internal static string btn_add_ingredients_Text {
            get {
                return ResourceManager.GetString("btn_add_ingredients.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Pedido.
        /// </summary>
        internal static string btn_add_order_Text {
            get {
                return ResourceManager.GetString("btn_add_order.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Tamanhos.
        /// </summary>
        internal static string btn_add_pizzas_sizes_Text {
            get {
                return ResourceManager.GetString("btn_add_pizzas_sizes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Produto.
        /// </summary>
        internal static string btn_add_products_Text {
            get {
                return ResourceManager.GetString("btn_add_products.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        internal static string btn_cancel_Text {
            get {
                return ResourceManager.GetString("btn_cancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string btn_clients_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_clients_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início.
        /// </summary>
        internal static string btn_dashboard_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_dashboard_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionários.
        /// </summary>
        internal static string btn_employees_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_employees_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Financeiro.
        /// </summary>
        internal static string btn_finances_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_finances_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedidos Abertos.
        /// </summary>
        internal static string btn_opened_orders_Text {
            get {
                return ResourceManager.GetString("btn_opened_orders.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedidos.
        /// </summary>
        internal static string btn_orders_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_orders_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamentos.
        /// </summary>
        internal static string btn_payments_Text {
            get {
                return ResourceManager.GetString("btn_payments.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pizzas.
        /// </summary>
        internal static string btn_products_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_products_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Receitas.
        /// </summary>
        internal static string btn_revenues_Text {
            get {
                return ResourceManager.GetString("btn_revenues.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string btn_save_Text {
            get {
                return ResourceManager.GetString("btn_save.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string btn_settings_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_settings_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque.
        /// </summary>
        internal static string btn_supply_nav_bar_Text {
            get {
                return ResourceManager.GetString("btn_supply_nav_bar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicional e Ingrediente.
        /// </summary>
        internal static string lbl_aditional_and_ingredient_Text {
            get {
                return ResourceManager.GetString("lbl_aditional_and_ingredient.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações Adicionais.
        /// </summary>
        internal static string lbl_aditional_info_Text {
            get {
                return ResourceManager.GetString("lbl_aditional_info.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string lbl_adress_complement_Text {
            get {
                return ResourceManager.GetString("lbl_adress_complement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Nascimento*.
        /// </summary>
        internal static string lbl_birth_date_Text {
            get {
                return ResourceManager.GetString("lbl_birth_date.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string lbl_category_Text {
            get {
                return ResourceManager.GetString("lbl_category.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Celular*.
        /// </summary>
        internal static string lbl_celphone_Text {
            get {
                return ResourceManager.GetString("lbl_celphone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF*.
        /// </summary>
        internal static string lbl_cpf_Text {
            get {
                return ResourceManager.GetString("lbl_cpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabor.
        /// </summary>
        internal static string lbl_flavour_Text {
            get {
                return ResourceManager.GetString("lbl_flavour.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número*.
        /// </summary>
        internal static string lbl_house_number_Text {
            get {
                return ResourceManager.GetString("lbl_house_number.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string lbl_ingredients_Text {
            get {
                return ResourceManager.GetString("lbl_ingredients.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicional?.
        /// </summary>
        internal static string lbl_is_aditional_Text {
            get {
                return ResourceManager.GetString("lbl_is_aditional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome*.
        /// </summary>
        internal static string lbl_name_Text {
            get {
                return ResourceManager.GetString("lbl_name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro*.
        /// </summary>
        internal static string lbl_neighborhood_Text {
            get {
                return ResourceManager.GetString("lbl_neighborhood.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente Adicional.
        /// </summary>
        internal static string lbl_only_as_aditional_Text {
            get {
                return ResourceManager.GetString("lbl_only_as_aditional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente Ingrediente.
        /// </summary>
        internal static string lbl_only_as_ingredient_Text {
            get {
                return ResourceManager.GetString("lbl_only_as_ingredient.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        internal static string lbl_package_quantity_Text {
            get {
                return ResourceManager.GetString("lbl_package_quantity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string lbl_password_Text {
            get {
                return ResourceManager.GetString("lbl_password.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações do Produto.
        /// </summary>
        internal static string lbl_product_info_Text {
            get {
                return ResourceManager.GetString("lbl_product_info.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        internal static string lbl_product_quantity_Text {
            get {
                return ResourceManager.GetString("lbl_product_quantity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preço de Venda.
        /// </summary>
        internal static string lbl_sale_price_Text {
            get {
                return ResourceManager.GetString("lbl_sale_price.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grande.
        /// </summary>
        internal static string lbl_size_big_Text {
            get {
                return ResourceManager.GetString("lbl_size_big.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gigante.
        /// </summary>
        internal static string lbl_size_giant_Text {
            get {
                return ResourceManager.GetString("lbl_size_giant.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Médio.
        /// </summary>
        internal static string lbl_size_medium_Text {
            get {
                return ResourceManager.GetString("lbl_size_medium.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pequeno.
        /// </summary>
        internal static string lbl_size_small_Text {
            get {
                return ResourceManager.GetString("lbl_size_small.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores.
        /// </summary>
        internal static string lbl_size_values_Text {
            get {
                return ResourceManager.GetString("lbl_size_values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanhos.
        /// </summary>
        internal static string lbl_sizes_Text {
            get {
                return ResourceManager.GetString("lbl_sizes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Admissão*.
        /// </summary>
        internal static string lbl_start_date_Text {
            get {
                return ResourceManager.GetString("lbl_start_date.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua*.
        /// </summary>
        internal static string lbl_street_Text {
            get {
                return ResourceManager.GetString("lbl_street.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        internal static string lbl_type_Text {
            get {
                return ResourceManager.GetString("lbl_type.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custo Unitário.
        /// </summary>
        internal static string lbl_unitary_cost_Text {
            get {
                return ResourceManager.GetString("lbl_unitary_cost.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade.
        /// </summary>
        internal static string lbl_unity_Text {
            get {
                return ResourceManager.GetString("lbl_unity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores.
        /// </summary>
        internal static string lbl_values_Text {
            get {
                return ResourceManager.GetString("lbl_values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warehouse_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("warehouse_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
